Use FramedStreamC for string -> message
Avoids the type-incompatibility between `Schema.Make (Capnp.BytesMessage)` and `Capnp.Codecs.FramedStream`:
  Error: This expression has type
         Schema.rw Capnp__Message.BytesMessage.Message.t
       but an expression was expected of type 'a ProjectSchema.message_t

at `ProjectSchema.Reader.RawMatchData.of_message message`

Why not fix? Too much time spent unsuccessfully finding which type equalities were missing in Tr1Capnp_Std.mli. And using FramedStreamC from DkSDKFFI_OCaml seems more consistent.