Merge of refactor2024 to main (#13)
* Add Develop compile-backend subcommand

* Upgrade SonicScout_Setup modules to fix new DkCoder alerts

- Qt needs Tr1Json_Std.Ezjsonm

https://gitlab.com/diskuv/sonicscout/scoutapps/-/issues/1

* Rename SonicScout_Std modules to match DkCoder

Simultaneously added 3rd party libraries to DkCoder. Those are mentioned below.

Refactorings:
- SquirrelScout_Std_intf -> Intf (since matched DkCoder library name). Added [sqlite3] library
- SquirrelScout_Std -> StdEntry (since matched DkCoder library name).
  Added [__init ()] to interface. Added module hacks to mitigate
  https://gitlab.com/diskuv/distributions/1.0/dksdk-coder/-/issues/7.
- Remove need for [vector] library
- team_names_table -> Team_names_table
- robot_pictures_table -> Robot_pictures_table
- qr_manager -> Qr_manager. Added [qrc] library
- match_schedule_table -> Match_schedule_table. Added [yojson] library
- db_utils -> Db_utils
- aws_manager -> Aws_manager
- main -> Main
- raw_match_data_table -> Raw_match_data_table
- schema -> Schema. Added [capnp] library

Imported:
- [logs] library

Added function aliases for compatibility with unshadowed OCaml:
- prerr_endline
- print_endline

Removed unused variables and prefix underscores to unused parameters.

https://gitlab.com/diskuv/sonicscout/scoutapps/-/issues/1

* Avoid now-removed Uutf library

* Download DkSDKFFI_OCaml binaries

- Make use of upstream codept fix for opened functor application
- Add [module _] expression for DkSDKFFI_OCaml

https://gitlab.com/diskuv/sonicscout/scoutapps/-/issues/1

* Upgrade dk from 2.1.3-2 to 2.1.4-r8

* Compile adjustments with DkCoder

+ Qualify cross-library modules with the library id
+ Add dune-file to optimize build times

https://gitlab.com/diskuv/sonicscout/scoutapps/-/issues/2

* Upgrade dk to 2.1.4-r9

* Compile adjustments with DkCoder (2/n)

https://gitlab.com/diskuv/sonicscout/scoutapps/-/issues/2

* Upgrade dk to 2.1.4-r10

* Use MlStd_Std.Exec in vscode

* Add marker files for Merlin to skip dune-project

* Upgrade ./dk: check for dkcoder-tool not dkcoder

* Use DkCoder .merlin development

* bugfix: Fail on failure of wsl --list

* Use refactored DkSDKFFI_OCaml

* Use FramedStreamC for string -> message

Avoids the type-incompatibility between `Schema.Make (Capnp.BytesMessage)` and `Capnp.Codecs.FramedStream`:
  Error: This expression has type
         Schema.rw Capnp__Message.BytesMessage.Message.t
       but an expression was expected of type 'a ProjectSchema.message_t

at `ProjectSchema.Reader.RawMatchData.of_message message`

Why not fix? Too much time spent unsuccessfully finding which type equalities were missing in Tr1Capnp_Std.mli. And using FramedStreamC from DkSDKFFI_OCaml seems more consistent.

* bugfix: Mitigate DkSDK CMake's lack of wrapping

In DkCoder libraries (packages in DkSDK CMake) inter-library modules are namespaced under the library name. DkSDK CMake works without that. So use DkCoder open__.ml to work in both contexts.

+ Provide imports for Us libraries in open__.ml

* Conform SquirrelScout_ObjsLib.ml to DkCoder standards

A script cannot have a basename that matches a DkCoder library id. So:

Introduced a submodule SquirrelScout_ObjsLib.Init that does the side-effects. SquirrelScout_ObjsLib.ml is just a wrapping library (only visible to DkSDK CMake).

* Upgrade ./dk to 2.2

* Regenerate from latest DkSDK CMake

* Conform OCaml to DkSDK CMake

* Upgrade ./dk to 2.2.1-4

* Work with DkSDK FFI OCaml 2.2.1

+ Switch from DkSDKFFI_OCaml-2.1.4 remote spec to DkSDKFFI_OCaml-2.2.1
+ Import DkCoder's Fpath and Cmdliner
+ Use DkCoder bridges for Fmt_cli, Logs_cli and Logs_fmt

* Use dksdk-cmake mastered branches

+ Tweaks from testing with DkSDK CMake
+ Use DKSDK_CMAKE_GITREF next with dksdk.project.get when --next
+ Change dkproject.jsonc to use dksdk-cmake versioned branches
+ No longer force the branches with DKSDK_*_BRANCH_1_0 environment variables since dkproject.jsonc now controls the branch more accurately (with versioned branches).
+ Add SonicScout_Objs/DkCoder_Std.ml to provide a typed no-op for DkSDK CMake
+ Expose SonicScout_Std.StdEntry as StdEntry for use in DkSDK CMake (which is a flat namespace)
+ Rename mock DkSDKFFI_OCaml to DkSDKFFI_OCaml0 to remove "make inconsistent assumptions" in DkSDK CMake over the real DkSDKFFI_OCaml

* Add Develop --skip-fetch

* Clean core/buildSrc/build

* Upgrade Java snapshots to 2.2.1

* Fetch dksdk-port-ocaml-ctypes

+ bugfix: Do dksdk.project.get when _not_ --skip-fetch

* Sync opam repositories with dkcoder

* Clean Android Gradle C++ artifacts during --dksdk-wsl2

* Remove Development tools from DkSDK CMake

Can use DkCoder much easier for ocaml lsp server and ocamlformat.

* Install local Python using uv

Fixes #2. Previously when using Anaconda/Miniconda we installed globally, and the global environment could be stale with packages that conflicted with scoutapps packages needed today,

+ Install uv
+ Remove Miniconda install and environment config
+ Use out-of-box IDE settings

* bugfix: Clean all dksdk and opam- directories

Found during https://github.com/diskuv/scoutapps/issues/14